// <script type="text/javascript">
var c=0;
function test()
{

if(document.getElementById('ra1').checked)
{
c+=1;
}
 if(document.getElementById('ra2').checked)
{
c+=1;
}
 if(document.getElementById('ra3').checked)
{
c+=1;
}
 if(document.getElementById('ra4').checked)
{
c+=1;
}
 if(document.getElementById('ra5').checked)
{
c+=1;
}
if(document.getElementById('ra6').checked)
{
c+=1;
}
if(document.getElementById('ra7').checked)
{
c+=1;
}
if(document.getElementById('ra8').checked)
{
c+=1;
}
if(document.getElementById('ra9').checked)
{
c+=1;
}
if(document.getElementById('ra10').checked)
{
c+=1;
}
if(document.getElementById('ra11').checked)
{
c+=1;
}
if(document.getElementById('ra12').checked)
{
c+=1;
}
if(document.getElementById('ra13').checked)
{
c+=1;
}
if(document.getElementById('ra14').checked)
{
c+=1;
}
if(document.getElementById('ra15').checked)
{
c+=1;
}
if(document.getElementById('ra16').checked)
{
c+=1;
}
if(document.getElementById('ra17').checked)
{
c+=1;
}
if(document.getElementById('ra18').checked)
{
c+=1;
}
if(document.getElementById('ra19').checked)
{
c+=1;
}
if(document.getElementById('ra20').checked)
{
c+=1;
}

console.log(c)
localStorage.setItem("c",c)
}
var d=0
function test1(){
if(document.getElementById('ra21').checked)
{
d+=1;
}
if(document.getElementById('ra22').checked)
{
d+=1;
}
if(document.getElementById('ra23').checked)
{
d+=1;
}
if(document.getElementById('ra24').checked)
{
d+=1;
}
if(document.getElementById('ra25').checked)
{
d+=1;
}
if(document.getElementById('ra26').checked)
{
d+=1;
}
if(document.getElementById('ra27').checked)
{
d+=1;
}
if(document.getElementById('ra28').checked)
{
d+=1;
}
if(document.getElementById('ra29').checked)
{
d+=1;
}
if(document.getElementById('ra30').checked)
{
d+=1;
}
if(document.getElementById('ra31').checked)
{
d+=1;
}
if(document.getElementById('ra32').checked)
{
d+=1;
}
if(document.getElementById('ra33').checked)
{
d+=1;
}
if(document.getElementById('ra34').checked)
{
d+=1;
}
if(document.getElementById('ra35').checked)
{
d+=1;
}
if(document.getElementById('ra36').checked)
{
d+=1;
}
if(document.getElementById('ra37').checked)
{
d+=1;
}
if(document.getElementById('ra38').checked)
{
d+=1;
}
if(document.getElementById('ra39').checked)
{
d+=1;
}
if(document.getElementById('ra40').checked)
{
d+=1;
}
console.log(d)
// var a=c+d;
// console.log(a)
localStorage.setItem("d",d)
a=parseInt(localStorage.getItem("c"))
b=parseInt(localStorage.getItem("d"))
	sum=a+b
// console.log(Number(localStorage.getItem("c"))+d)
if(sum<20)
document.write("your score is:"+sum +" "+"The minimum score to pass is 20 .Better luck next time");
else
document.write("your score is:"+sum +" "+"Congratulations! You have cleared section A and B.You are now eligible for section C");
}
// </script>