// <script type="text/javascript">
var c=0;
function test4()
{

if(document.getElementById('na1').checked)
{
c+=1;
}
 if(document.getElementById('na2').checked)
{
c+=1;
}
 if(document.getElementById('na3').checked)
{
c+=1;
}
 if(document.getElementById('na4').checked)
{
c+=1;
}
 if(document.getElementById('na5').checked)
{
c+=1;
}
if(document.getElementById('na6').checked)
{
c+=1;
}
if(document.getElementById('na7').checked)
{
c+=1;
}
if(document.getElementById('na8').checked)
{
c+=1;
}
if(document.getElementById('na9').checked)
{
c+=1;
}
if(document.getElementById('na10').checked)
{
c+=1;
}
if(document.getElementById('na11').checked)
{
c+=1;
}
if(document.getElementById('na12').checked)
{
c+=1;
}
if(document.getElementById('na13').checked)
{
c+=1;
}
if(document.getElementById('na14').checked)
{
c+=1;
}
if(document.getElementById('na15').checked)
{
c+=1;
}
if(document.getElementById('na16').checked)
{
c+=1;
}
if(document.getElementById('na17').checked)
{
c+=1;
}
if(document.getElementById('na18').checked)
{
c+=1;
}
if(document.getElementById('na19').checked)
{
c+=1;
}
if(document.getElementById('na20').checked)
{
c+=1;
}

console.log(c)
localStorage.setItem("c",c)
}
var d=0
function test5(){
if(document.getElementById('na21').checked)
{
d+=1;
}
if(document.getElementById('na22').checked)
{
d+=1;
}
if(document.getElementById('na23').checked)
{
d+=1;
}
if(document.getElementById('na24').checked)
{
d+=1;
}
if(document.getElementById('na25').checked)
{
d+=1;
}
if(document.getElementById('na26').checked)
{
d+=1;
}
if(document.getElementById('na27').checked)
{
d+=1;
}
if(document.getElementById('na28').checked)
{
d+=1;
}
if(document.getElementById('na29').checked)
{
d+=1;
}
if(document.getElementById('na30').checked)
{
d+=1;
}
if(document.getElementById('na31').checked)
{
d+=1;
}
if(document.getElementById('na32').checked)
{
d+=1;
}
if(document.getElementById('na33').checked)
{
d+=1;
}
if(document.getElementById('na34').checked)
{
d+=1;
}
if(document.getElementById('na35').checked)
{
d+=1;
}
if(document.getElementById('na36').checked)
{
d+=1;
}
if(document.getElementById('na37').checked)
{
d+=1;
}
if(document.getElementById('na38').checked)
{
d+=1;
}
if(document.getElementById('na39').checked)
{
d+=1;
}
if(document.getElementById('na40').checked)
{
d+=1;
}
console.log(d)
// var a=c+d;
// console.log(a)
localStorage.setItem("d",d)
a=parseInt(localStorage.getItem("c"))
b=parseInt(localStorage.getItem("d"))
	sum=a+b
// console.log(Number(localStorage.getItem("c"))+d)
if(sum<20)
document.write("your score is:"+sum +" "+"The minimum score to pass is 20 .Better luck next time");
else
document.write("your score is:"+sum +" "+"Congratulations! You have cleared section A and B.You are now eligible for section C");
}
// </script>